- insalan/user/tests.py
- insalan/user/views.py
Intends to fix #59 last comment
> 🐛 Caught ValidationErrors and throw a Bad Request instead

- insalan/user/models.py
- insalan/user/tests.py
- Change url in password resetting mail from backend to frontend.
- Fix corresponding tests.
> Password reset mail

- insalan/payment/hooks.py
- insalan/payment/models.py
- insalan/payment/tokens.py
- locale/en/LC_MESSAGES/django.po
I also found a couple of strings here and there that I had put in the gettext call but written in english :sweat_smile:
> More updates for translations

- CONTRIBUTING.md
- README.md
Added a first version of `CONTRIBUTING.md` adapted from the contributor covenant.
Once accepted and merged, we will duplicate it on the two other website's repos.
> 📜 Added a first version of `CONTRIBUTING.md`

- insalan/user/admin.py
Just a small change that allow better navigation in the user admin panel
> Add custom ordering and filter to user Admin panel

- insalan/payment/tokens.py
- insalan/payment/views.py
> Fix missing timeout

- Dockerfile
- Dockerfile.dev
Fix image used by dockerfile using latest.
> Fix dockerfile version not static

- insalan/tournament/admin.py
- insalan/user/admin.py
Now it's beautiful and usable !
Add sort option and add better display field on tournament pages.
> Improve admin panel usability for my beloved tournament team

- insalan/payment/views.py
Remove a lot of raw accesses to the data dictionary in the payment notification view, and check them for presence and type when used, with logging added.
---
You've really gotta help me review this one. The code here has to work exactly the same as it did before, but without the vulnerable dictionary queries. One of the step of hardening was determining types, and without being able to deploy and test, I had to rely on past behaviour + documentation.
**We really have to make sure this code works as it used to**
> Harden payment notification reception path

- insalan/payment/views.py
Guess what, everything was not fine with #111
Fixed in prod atm but better to merge this nicely.
https://stackoverflow.com/questions/24463202/typeerror-get-takes-no-keyword-arguments
> Fix dict.get default unamed

- insalan/payment/admin.py
- insalan/tickets/admin.py
- insalan/tournament/admin.py
Fix #106
Field had to be deref in search fields. Explanation can be found here : https://stackoverflow.com/questions/11754877/troubleshooting-related-field-has-invalid-lookup-icontains
> Fix 500 when searching in admin panel

- insalan/tournament/tests.py
- insalan/tournament/views.py
https://github.com/InsaLan/frontend-insalan.fr/pull/76
> Add the payment status of the players in the tournaments informations

- insalan/settings.py
overwrite SESSION_COOKIE_AGE in django settings.
> Change settings to overwrite SESSION_COOKIE_AGE

- insalan/urls.py
> Change "View Site" button url to frontend

- insalan/tournament/admin.py
Fix this bug cause i introduced changes in a PR without testing everything.
> Fix change team password showing 500

- insalan/user/admin.py
Add a button to resend the confirmation mail to a user. 
This Button is only visible when user has not already confirmed his email.
> Add resend mail button to admin panel

- insalan/cms/models.py
when content is saved and it's name is planing, apply some operations to change the colours to look nicer on the frontend.
> Apply some operations on the content to make it look better when it's planning

- insalan/cms/models.py
- insalan/tournament/models.py
- insalan/tournament/tests.py
> Tournament plannings

- insalan/langate/models.py
- insalan/langate/serializers.py
Added data about whether a user is staff or admin to the langate authentication endpoint (tested by hand only)
> ⚙ Added helper fields for langate staff autologin

- insalan/payment/admin.py
- insalan/pizza/admin.py
- insalan/pizza/models.py
- insalan/pizza/serializers.py
This PR add an export action for my beloved Treasurer. The format was chose with him and can always be changed if needed later.
> Pizza and Payment export admin

- insalan/tournament/models/bracket.py
- insalan/tournament/models/event.py
- insalan/tournament/models/game.py
- insalan/tournament/models/group.py
- insalan/tournament/models/match.py
- insalan/tournament/models/player.py
- insalan/tournament/models/substitute.py
- insalan/tournament/models/swiss.py
- insalan/tournament/models/team.py
- insalan/tournament/models/tournament.py
- insalan/tournament/serializers.py
- insalan/tournament/tests.py
- insalan/tournament/views/manager.py
- insalan/tournament/views/player.py
- insalan/tournament/views/substitute.py
- insalan/tournament/views/team.py
- insalan/tournament/views/tournament.py
Optimize the code for the tournament/full endpoint to reduce the load on the db (reduce number of query) and also reduce the response time.
Also update some things like prevent 500 on some endpoints and craps.
The response time on the bellow screens is not the real one because of the module i used to intercept the response. But you can compare both of them.
Before : 
After :
> Optimize tournament/full

- insalan/user/models.py
This pull request automatically add the email_active permission to the superuser so he can login.
Fix #150
> Fix superuser not able to connect

- insalan/tournament/models/validators.py
Fix little bug in name validator
#166
> Fix Name validator

- insalan/tournament/views/tournament.py
Fix inconsistency in fields name for matches.
- [N/A] I have added tests to cover my changes.
- [N/A] I have updated the documentation accordingly.
- [N/A] I have assigned the pull request to the appropriate reviewer(s).
https://github.com/InsaLan/frontend-insalan.fr/issues/129
> Fix swiss match having wrong field name in tournament API

- insalan/pizza/models.py
- insalan/pizza/serializers.py
- insalan/pizza/tests.py
- insalan/pizza/views.py
This pull requests prevent the same order to be send twice in a short amount of time.
Fix: #143
> Prevent order dupplication in pizza app

- .github/workflows/ci.yaml
- .pylintrc
- Dockerfile.dev
- requirements-dev.txt
Add pylint as a dev dependencies so it run in the same environment in all case.
Please list any related issues or pull requests here.
If applicable, add screenshots to help explain the changes made.
> Add pylint in dev dependencies

- insalan/tournament/models/event.py
- insalan/tournament/serializers.py
- insalan/tournament/tests.py
Add poster field in the event model.
This will allow us to add it on the frontend.
> Add poster field

- insalan/tournament/models/tournament.py
- insalan/tournament/tests.py
Add bottom description field in tournament.
Needed for <https://github.com/InsaLan/frontend-insalan.fr/pull/167>
> Add bottom description field in tournament

- insalan/pizza/tests.py
- insalan/pizza/urls.py
- insalan/pizza/views.py
Add an endpoint allowing export download.
Fix https://github.com/InsaLan/frontend-insalan.fr/issues/150
> Add an endpoint to download exports

- assets/js/seat_canvas.js
This PR add a scroll bar when the canvas is too large for the page
Fix #186
> Fix tournament seating overflow

- insalan/cms/models.py
- insalan/tournament/models/event.py
- insalan/tournament/models/tournament.py
- insalan/tournament/serializers.py
- insalan/tournament/tests.py
change planning handling from gdoc hardcoded shit to .ics file upload.
Please list any related issues or pull requests here.
If applicable, add screenshots to help explain the changes made.
> Improve Planning upload

- insalan/tournament/admin.py
- insalan/tournament/manage/bracket.py
- insalan/tournament/manage/group.py
- insalan/tournament/manage/match.py
- insalan/tournament/manage/swiss.py
- insalan/tournament/models/__init__.py
- insalan/tournament/models/bracket.py
- insalan/tournament/models/group.py
- insalan/tournament/models/match.py
- insalan/tournament/models/swiss.py
- insalan/tournament/models/team.py
- insalan/tournament/models/tournament.py
- insalan/tournament/models/validators.py
- insalan/tournament/serializers.py
- insalan/tournament/tests.py
- insalan/tournament/urls.py
- insalan/tournament/views/bracket.py
- insalan/tournament/views/event.py
- insalan/tournament/views/game.py
- insalan/tournament/views/group.py
- insalan/tournament/views/manager.py
- insalan/tournament/views/player.py
- insalan/tournament/views/substitute.py
- insalan/tournament/views/swiss.py
- insalan/tournament/views/team.py
- insalan/tournament/views/tournament.py
The objective is to provide a better user interface for the admin tournament team to manage tournaments.
See https://github.com/InsaLan/frontend-insalan.fr/pull/173.
> Frontend for tournament administration
